name: Build
on: 
  release:
    types:
      - created
      
env:
  DOTNET_INSTALL_DIR: "runner/dotnet"
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: setup .NET core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          
          
      - name: sql package
        run: dotnet tool install -g microsoft.sqlpackage
         
      - name: sql build
        run: dotnet build demo-db.sqlproj -p:NetCoreBuild -c Release
         
      - name: Zip DACPAC
        run: |
          cd ./bin/Release
          zip -r dacpac.zip ./
           
      - name: list
        run: |
          cd ./bin/Release
          ls
           
      - name: setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3.2.0
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          URL: https://durga1212.jfrog.io
          
      - name: upload package to artifact
        run: |
         curl -uprasadkesari329.dk@gmail.com:$ARTIFACTORY_PASSWORD -T dacpac.zip "https://durga1212.jfrog.io/artifactory/generic-release/"
         
